all: program1-arrays program1-arrayptrs program1-natptrs program2-arrays program2-arrayptrs program2-natptrs

program1-arrays: program1-arrays.c
	gcc -o program1-arrays program1-arrays.c

program1-arrayptrs: program1-arrayptrs.c
	gcc -o program1-arrayptrs program1-arrayptrs.c

program1-natptrs: program1-natptrs.c
	gcc -o program1-natptrs program1-natptrs.c

program2-arrays: program2-arrays.c
	gcc -o program2-arrays program2-arrays.c

program2-arrayptrs: program2-arrayptrs.c
	gcc -o program2-arrayptrs program2-arrayptrs.c

program2-natptrs: program2-natptrs.c
	gcc -o program2-natptrs program2-natptrs.c

clean:
	rm -f program1-arrays program1-arrayptrs program1-natptrs program2-arrays program2-arrayptrs program2-natptrs